"""empty message

Revision ID: 0c3e84ddf38c
Revises: 1620844911ae
Create Date: 2018-07-16 22:04:16.308761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3e84ddf38c'
down_revision = '1620844911ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asset',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=45), nullable=True),
    sa.Column('sn', sa.String(length=45), nullable=True),
    sa.Column('buy_time', sa.DateTime(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=128), nullable=True),
    sa.Column('disk', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('cpu_model', sa.String(length=128), nullable=True),
    sa.Column('cpu_processor', sa.String(length=32), nullable=True),
    sa.Column('cpu_num', sa.String(length=32), nullable=True),
    sa.Column('cpu_physical', sa.String(length=32), nullable=True),
    sa.Column('business_unit', sa.String(length=45), nullable=True),
    sa.Column('idc', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('sn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Asset')
    # ### end Alembic commands ###
