"""empty message

Revision ID: 1620844911ae
Revises: f06cb8afc691
Create Date: 2018-07-16 21:41:11.516853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1620844911ae'
down_revision = 'f06cb8afc691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Asset', sa.Column('cpu_processor', sa.String(length=32), nullable=True))
    op.drop_column('Asset', 'cpu_cores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Asset', sa.Column('cpu_cores', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('Asset', 'cpu_processor')
    # ### end Alembic commands ###
