"""del forien

Revision ID: 848bdc07aab9
Revises: 
Create Date: 2018-07-11 14:49:33.932210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '848bdc07aab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asset',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('sn', sa.String(length=45), nullable=True),
    sa.Column('buy_time', sa.DateTime(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('management_ip', sa.Integer(), nullable=True),
    sa.Column('business_unit', sa.String(length=45), nullable=True),
    sa.Column('idc', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sn')
    )
    op.create_table('BusinessUnit',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('memo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IDC',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('memo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Manufactory',
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('manufactory', sa.String(length=45), nullable=True),
    sa.Column('support_num', sa.String(length=30), nullable=True),
    sa.Column('memo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('businessunit')
    op.drop_table('manufactory')
    op.drop_index('name', table_name='asset')
    op.drop_index('sn', table_name='asset')
    op.drop_table('asset')
    op.drop_table('idc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idc',
    sa.Column('id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('memo', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('asset',
    sa.Column('id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('sn', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('buy_time', mysql.DATETIME(), nullable=True),
    sa.Column('expire_date', mysql.DATETIME(), nullable=True),
    sa.Column('management_ip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('idc_id', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('memo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.Column('approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idc_id'], ['idc.id'], name='asset_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('sn', 'asset', ['sn'], unique=True)
    op.create_index('name', 'asset', ['name'], unique=True)
    op.create_table('manufactory',
    sa.Column('id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('manufactory', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('support_num', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('memo', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('businessunit',
    sa.Column('id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('memo', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Manufactory')
    op.drop_table('IDC')
    op.drop_table('BusinessUnit')
    op.drop_table('Asset')
    # ### end Alembic commands ###
