"""empty message

Revision ID: 937b6ddfd839
Revises: 891cb151e421
Create Date: 2018-07-14 11:13:11.537315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937b6ddfd839'
down_revision = '891cb151e421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Asset', sa.Column('model', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Asset', 'model')
    # ### end Alembic commands ###
