"""model

Revision ID: c36571f7facd
Revises: e86fed540063
Create Date: 2018-07-14 11:16:46.330374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36571f7facd'
down_revision = 'e86fed540063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Asset', sa.Column('status', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Asset', 'status')
    # ### end Alembic commands ###
