"""empty message

Revision ID: f06cb8afc691
Revises: 
Create Date: 2018-07-16 21:35:26.716949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f06cb8afc691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Asset', sa.Column('cpu_cores', sa.String(length=32), nullable=True))
    op.add_column('Asset', sa.Column('cpu_model', sa.String(length=128), nullable=True))
    op.add_column('Asset', sa.Column('cpu_num', sa.String(length=32), nullable=True))
    op.add_column('Asset', sa.Column('cpu_physical', sa.String(length=32), nullable=True))
    op.add_column('Asset', sa.Column('disk', sa.String(length=128), nullable=True))
    op.add_column('Asset', sa.Column('hostname', sa.String(length=45), nullable=True))
    op.add_column('Asset', sa.Column('ip', sa.String(length=128), nullable=True))
    op.add_column('Asset', sa.Column('memory', sa.Integer(), nullable=True))
    op.add_column('Asset', sa.Column('model', sa.String(length=45), nullable=True))
    op.drop_index('name', table_name='Asset')
    op.create_unique_constraint(None, 'Asset', ['hostname'])
    op.drop_column('Asset', 'management_ip')
    op.drop_column('Asset', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Asset', sa.Column('name', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('Asset', sa.Column('management_ip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Asset', type_='unique')
    op.create_index('name', 'Asset', ['name'], unique=True)
    op.drop_column('Asset', 'model')
    op.drop_column('Asset', 'memory')
    op.drop_column('Asset', 'ip')
    op.drop_column('Asset', 'hostname')
    op.drop_column('Asset', 'disk')
    op.drop_column('Asset', 'cpu_physical')
    op.drop_column('Asset', 'cpu_num')
    op.drop_column('Asset', 'cpu_model')
    op.drop_column('Asset', 'cpu_cores')
    # ### end Alembic commands ###
